### ISSUE TITLE
nv/target: No such file or directory

### ISSUE THREAD

**Issue by jabowery** [NX-AI/xlstm#13]
After adding `ninja` to the conda environment:
```
(xlstm) jabowery@jaboweryML:~/devel/xlstm$ cat environment.yml 
name: xlstm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - ninja
  - cuda=12.1
  - cuda-nvcc=12.1
  - gxx_linux-64=11.2.0
  - python=3.11
  - pip
  - pytorch=2.2.0
  - pytorch-cuda=12.1
  - cmake #=3.28.2
  - pip:
      - pre-commit #==3.6.0
      - ipykernel #==6.29.0
      - dacite #==1.8.1
      - omegaconf #==2.3.0
      - torchmetrics #==1.3.0
      - tqdm #==4.66.1
      - pytest #==8.0.0
      - pytest-xdist #==3.5.0
      - numpy #==1.26.4
(xlstm) jabowery@jaboweryML:~/devel/xlstm$ mamba env update --file environment.yml --prune

```
to fix [this issue](https://github.com/NX-AI/xlstm/issues/12):
(xlstm) jabowery@jaboweryML:~/devel/xlstm$ python experiments/main.py --config experiments/parity_xlstm01.yaml
...
FAILED: slstm_backward.cuda.o 
...
In file included from /home/jabowery/mambaforge/envs/xlstm/include/cuda_fp16.h:4019,
                 from /home/jabowery/mambaforge/envs/xlstm/include/cublas_api.h:77,
                 from /home/jabowery/mambaforge/envs/xlstm/include/cublas_v2.h:69,
                 from /home/jabowery/devel/xlstm/xlstm/blocks/slstm/src/cuda/slstm_backward.cu:22:
/home/jabowery/mambaforge/envs/xlstm/include/cuda_fp16.hpp:65:10: fatal error: nv/target: No such file or directory
   65 | #include <nv/target>
      |          ^~~~~~~~~~~
compilation terminated.
...

**Comment by alexarnimueller** [comment]
I run into the same issue, after a manual pip install Ninja though

**Comment by alexarnimueller** [comment]
`conda install cccl` solved it for me

**Comment by kpoeppel** [comment]
Updated the environment file.
