### ISSUE TITLE
input about variable sequence length

### ISSUE THREAD

**Issue by llllly26** [NX-AI/xlstm#15]
Hi, I want to know that if the input data has `[pad]` token, how to solve it? and xLSTM don't support `PackedSequence` object.

**Comment by louyongjun** [comment]
Hello, yesterday I saw that you had this problem, have you resolved it
RuntimeError: Error building extension 'slstm_HS128BS8NH4NS4DBfDRbDWbDGbDSbDAfNG4SA1GRCV0GRC0d0FCV0FC0d0'

**Comment by a13382735176** [comment]
你们代码都能跑吗？

**Comment by kpoeppel** [comment]
Check the lasted environment yaml. For now PackedSequence is not supported, but you can write a wrapper yourself.
